const MIN=60000;
function incident(type,events,score,mitre,reason){const sorted=[...events].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)),risk=Math.min(100,score),users=[...new Set(events.map(e=>e.username))],sourceIps=[...new Set(events.map(e=>e.source_ip))],key=`${type}|${sourceIps.join(',')}|${users.slice(0,2).join(',')}|${sorted[0]?.timestamp}`;let hash=0;for(const c of key)hash=(hash*31+c.charCodeAt(0))|0;return {id:`INC-${type.slice(0,3).toUpperCase()}-${Math.abs(hash).toString(36).slice(0,5).toUpperCase()}`,type,attackType:type,source_ip:sourceIps[0],sourceIps,users,affectedUsers:users,first_seen:sorted[0]?.timestamp,last_seen:sorted.at(-1)?.timestamp,attempts:events.length,risk,riskScore:risk,severity:risk>=80?'CRITICAL':risk>=60?'HIGH':risk>=30?'MEDIUM':'LOW',confidence:Math.max(61,Math.min(98,Math.round(62+Math.max(0,risk-40)*.62))),mitre,mitreTechnique:mitre,reason,explanation:reason,status:'Open',events:sorted};}
export function detectBruteForce(events){const out=[],by=new Map();for(const e of events.filter(e=>e.result==='failure')){if(!by.has(e.username))by.set(e.username,[]);by.get(e.username).push(e);}for(const [user,arr] of by){arr.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let end=0;for(let i=0;i<arr.length;i++){while(end<arr.length&&Date.parse(arr[end].timestamp)-Date.parse(arr[i].timestamp)<=5*MIN)end++;if(end-i>=10){const group=arr.slice(i,end),ips=new Set(group.map(e=>e.source_ip)),distributed=ips.size>=3,type=distributed?'Distributed Brute Force':'Brute Force',technique='T1110.001',score=Math.min(99,45+group.length*3+(distributed?8:0));out.push(incident(type,group,score,technique,`${group.length} failed attempts targeted ${user} within five minutes${distributed?`, distributed across ${ips.size} source IPs`:''}.`));i=end-1;}}}return out;}
export function detectPasswordSpray(events){const out=[],by=new Map();for(const e of events.filter(e=>e.result==='failure')){if(!by.has(e.source_ip))by.set(e.source_ip,[]);by.get(e.source_ip).push(e);}for(const [ip,arr] of by){arr.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let end=0;for(let i=0;i<arr.length;i++){while(end<arr.length&&Date.parse(arr[end].timestamp)-Date.parse(arr[i].timestamp)<=10*MIN)end++;const group=arr.slice(i,end),users=new Set(group.map(e=>e.username));if(users.size>=10&&group.length/users.size<=5){const score=Math.min(99,55+users.size);out.push(incident('Password Spray',group,score,'T1110.003',`${users.size} users received ${group.length} failed attempts from one source within ten minutes.`));i=end-1;}}}return out;}
const LOC={US:[39,-98],GB:[55,-3],IN:[21,78],DE:[51,10],FR:[46,2],CA:[56,-106],AU:[-25,133],JP:[36,138],BR:[-10,-55]};
function distance(a,b){const rad=x=>x*Math.PI/180;const [x,y]=a.map(rad),[u,v]=b.map(rad),dX=u-x,dY=v-y;return 6371*2*Math.asin(Math.sqrt(Math.sin(dX/2)**2+Math.cos(x)*Math.cos(u)*Math.sin(dY/2)**2));}
export function detectImpossibleTravel(events){const out=[];const by=new Map();for(const e of events.filter(x=>x.result==='success')){if(!by.has(e.username))by.set(e.username,[]);by.get(e.username).push(e);}for(const [user,arr] of by){arr.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));for(let i=1;i<arr.length;i++){const a=arr[i-1],b=arr[i],la=LOC[a.country?.toUpperCase()],lb=LOC[b.country?.toUpperCase()];if(!la||!lb||a.source_ip===b.source_ip)continue;const km=distance(la,lb),hours=(Date.parse(b.timestamp)-Date.parse(a.timestamp))/3600000;if(km>500&&hours>0&&km/hours>900){out.push(incident('Impossible Travel',[a,b],Math.min(99,75+Math.round(km/1000*10)),'T1078',`Successful logins from ${a.country} and ${b.country}; estimated travel speed ${Math.round(km/hours)} km/h.`));}}}return out;}
export function detectCredentialStuffing(events){const out=[],by=new Map();for(const e of events.filter(e=>e.result==='failure')){if(!by.has(e.source_ip))by.set(e.source_ip,[]);by.get(e.source_ip).push(e);}for(const [ip,arr] of by){arr.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let end=0;for(let i=0;i<arr.length;i++){while(end<arr.length&&Date.parse(arr[end].timestamp)-Date.parse(arr[i].timestamp)<=10*MIN)end++;const group=arr.slice(i,end),users=new Set(group.map(e=>e.username)),avg=group.length/Math.max(1,users.size);if(users.size>=5&&group.length>=30&&avg>5){out.push(incident('Credential Stuffing',group,Math.min(98,72+users.size),'T1110.004',`${group.length} failures targeted ${users.size} accounts from ${ip} in ten minutes (${avg.toFixed(1)} attempts/user), consistent with credential stuffing.`));i=end-1;}}}return out;}
export function detectAbnormalLoginBurst(events){const out=[],by=new Map();for(const e of events){if(!by.has(e.source_ip))by.set(e.source_ip,[]);by.get(e.source_ip).push(e);}for(const [ip,arr] of by){arr.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let end=0;for(let i=0;i<arr.length;i++){while(end<arr.length&&Date.parse(arr[end].timestamp)-Date.parse(arr[i].timestamp)<=MIN)end++;const group=arr.slice(i,end),users=new Set(group.map(e=>e.username));if(group.length>=30&&users.size>=10){out.push(incident('Abnormal Login Burst',group,Math.min(96,65+Math.floor(group.length/3)),'T1110',`${group.length} authentication attempts across ${users.size} users came from ${ip} within one minute.`));i=end-1;}}}return out;}
export function detectAccountEnumeration(events){const evidence=events.filter(e=>e.result==='failure'&&Object.values(e.raw||{}).some(v=>/unknown user|user not found|invalid username|account does not exist/i.test(String(v))));const by=new Map();for(const e of evidence){if(!by.has(e.source_ip))by.set(e.source_ip,[]);by.get(e.source_ip).push(e);}const out=[];for(const [ip,arr] of by){const users=new Set(arr.map(e=>e.username));if(users.size>=5)out.push(incident('Account Enumeration',arr,Math.min(92,62+users.size),'T1087',`${users.size} distinct unknown or invalid account names were rejected from ${ip}; this can indicate account enumeration.`));}return out;}
export function runDetection(events){return [...detectBruteForce(events),...detectPasswordSpray(events),...detectImpossibleTravel(events),...detectCredentialStuffing(events),...detectAbnormalLoginBurst(events),...detectAccountEnumeration(events)].sort((a,b)=>b.risk-a.risk);}

