const ATTACKS=new Set(['Brute Force','Password Spray','Impossible Travel','Credential Stuffing','Distributed Brute Force','Account Enumeration','Distributed Authentication Attack','Abnormal Login Burst']);
export const countryName=value=>({US:'United States',GB:'United Kingdom',IN:'India',DE:'Germany',FR:'France',CA:'Canada',AU:'Australia',JP:'Japan',BR:'Brazil'}[String(value||'').toUpperCase()]||value||'Unknown');
export function incidentEvents(incidents){return new Set(incidents.flatMap(i=>i.events));}
export function eventRisk(event,incidents){const hits=incidents.filter(i=>i.events.includes(event));return hits.length?Math.max(...hits.map(i=>i.risk)):event.result==='failure'?24:8;}
export function eventStatus(event,incidents){return incidents.some(i=>i.events.includes(event))?'ATTACK DETECTED':event.result==='failure'?'SUSPICIOUS':'NORMAL';}
export function confidenceFor(incident){return Math.max(61,Math.min(98,Math.round(62+Math.max(0,incident.risk-40)*.62)));}
export function scoreSeverity(score){return score>=80?'CRITICAL':score>=60?'HIGH':score>=30?'MEDIUM':'LOW';}
export function userSummary(user,events,incidents){const rows=events.filter(e=>e.username===user),bad=incidentEvents(incidents);const relevant=incidents.filter(i=>i.users.includes(user));const failed=rows.filter(e=>e.result==='failure').length;return {user,rows,failed,successes:rows.length-failed,ips:[...new Set(rows.map(e=>e.source_ip))],devices:[...new Set(rows.map(e=>e.device).filter(Boolean))],locations:[...new Set(rows.map(e=>countryName(e.country)))],risk:relevant.length?Math.max(...relevant.map(i=>i.risk)):Math.min(59,failed*8),status:relevant.length?'ATTACK DETECTED':failed>=3?'SUSPICIOUS':'NORMAL',relatedUsers:[...new Set(relevant.flatMap(i=>i.users).filter(x=>x!==user))],attacks:relevant.map(i=>i.type),bad};}
export function ipSummary(ip,events,incidents){const rows=events.filter(e=>e.source_ip===ip),attacks=incidents.filter(i=>i.source_ip===ip||i.events.some(e=>e.source_ip===ip));const failed=rows.filter(e=>e.result==='failure').length;return {ip,rows,failed,successes:rows.length-failed,users:[...new Set(rows.map(e=>e.username))],devices:[...new Set(rows.map(e=>e.device).filter(Boolean))],locations:[...new Set(rows.map(e=>countryName(e.country)))],firstSeen:rows[0]?.timestamp,lastSeen:rows.at(-1)?.timestamp,risk:attacks.length?Math.max(...attacks.map(i=>i.risk)):Math.min(59,failed*7),attacks};}
export function detectionSignals(incident,allEvents){const rows=incident.events,minutes=Math.max(.1,(Date.parse(incident.last_seen)-Date.parse(incident.first_seen))/60000),ips=[...new Set(rows.map(e=>e.source_ip))],countries=[...new Set(rows.map(e=>countryName(e.country)))],devices=[...new Set(rows.map(e=>e.device).filter(Boolean))];const unfamiliar=incident.users.filter(user=>{const known=new Set(allEvents.filter(e=>e.username===user&&!rows.includes(e)).map(e=>e.source_ip));return !known.has(incident.source_ip);}).length;const rhythm=`${rows.length} authentication events over ${minutes.toFixed(1)} minutes (${(rows.length/minutes).toFixed(1)} events/minute); ${rows.filter(e=>e.result==='failure').length} failures.`;const context=`${incident.users.length} account(s), ${countries.length} location(s), ${devices.length} device profile(s); the source is new for ${unfamiliar} affected user(s) in this loaded sample.`;const shape=`${ips.length} source IP(s) connected to ${incident.users.length} user(s); ${rows.length} source-user events form the detected pattern.`;return {rhythm,context,shape,unfamiliarUsers:unfamiliar,countries,devices,ips,minutes};}
export function topCounts(events,key,limit=5){const map=new Map();for(const e of events){const val=e[key]||'Unknown';map.set(val,(map.get(val)||0)+1);}return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit);}
export function isSupportedAttack(type){return ATTACKS.has(type);}

